name: peom_puzzle
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/

  fonts:
    - family: Plaster
      fonts:
        - asset: asset/fonts/plaster/Plaster-Regular.ttf
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto/Roboto-Regular.ttf