name: poem_puzzle
description: 一个古诗拼图应用
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/datas/

  fonts:
    - family: Plaster
      fonts:
        - asset: asset/fonts/plaster/Plaster-Regular.ttf
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto/Roboto-Regular.ttf
    - family: NotoSansSC
      fonts:
        - asset: asset/fonts/NotoSansSC/NotoSansSC-6.ttf
    - family: Noto Sans SC
      fonts:
        - asset: asset/fonts/NotoSansSC/NotoSansSC-6.ttf